#!/usr/bin/python3
""" unittt test for basessss """
import json
import unittest
from models.base_model import BaseModel
from datetime import datetime
import models
import sys



class BaseModelTestCase(unittest.TestCase):
    """ classss for base testtt """
    pass


if __name__ == '__main__':
    unittest.main()
